name: "Label PR by Directory"
description: "Adds a label to PRs for each top-level directory touched"
inputs:
  github_token:
    description: "GitHub Token"
    required: true
runs:
  using: "node20"
  main: "index.js"
